openapi: 3.0.1
info:
  description: |
    SyskenGachaのバックエンド。
  title: SyskenGacha-backend
  version: 1.0.0
servers:
- url: /backend/
paths:
  /gacha:
    get:
      description: ガチャにて排出される全アイテムのリスト
      operationId: gacha_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GachaItem'
          description: 正常時のレスポンス
      summary: ガチャリスト
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /gacha/{ItemId}:
    get:
      description: ガチャアイテム
      operationId: gacha_item_id_get
      parameters:
      - description: ガチャID
        explode: false
        in: path
        name: ItemId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GachaList'
          description: 正常なレスポンス
      summary: ガチャアイテム
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /gacha/random/:
    get:
      description: ランダムなガチャアイテム
      operationId: random_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GachaItem'
          description: 正常なレスポンス
      summary: ランダムなガチャアイテム
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /gacha/static/{PictId}:
    get:
      description: 指定されたIdの画像を返却します
      operationId: static_pict_id_get
      parameters:
      - description: 取得したい画像の連番ID
        explode: false
        in: path
        name: PictId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          description: 存在時のレスポンス
          content:
            image/jpg:
              schema:
                format: binary
                type: string
                x-content-type: image/jpg

      summary: 画像
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /admin/item:
    put:
      description: アイテムの編集
      operationId: admin_item_put
      parameters:
      - description: ID
        explode: false
        in: query
        name: id
        required: true
        schema:
          format: int64
          type: integer
      - description: アイテム名
        explode: false
        in: query
        name: name
        required: true
        schema:
          type: string
      - description: レアリティ
        explode: false
        in: query
        name: rare
        required: true
        schema:
          type: integer
      - description: 画像ID
        explode: false
        in: query
        name: image
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GachaItem'
          description: 正常なレスポンス
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GachaItem'
          description: リクエストが不正な場合
      x-openapi-router-controller: openapi_server.controllers.security_controller
    post:
      description: アイテムの追加
      operationId: admin_item_post
      parameters:
      - description: アイテム名
        explode: false
        in: query
        name: name
        required: true
        schema:
          type: string
      - description: レアリティ
        explode: false
        in: query
        name: rare
        required: true
        schema:
          format: int64
          type: integer
      - description: 画像ID
        explode: false
        in: query
        name: image
        required: false
        schema:
          type: string
      responses:
          "200":
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/GachaItem'
            description: 正常なレスポンス
          "400":
            content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/GachaItem'
            description: リクエストが不正な場合
      x-openapi-router-controller: openapi_server.controllers.security_controller
  /admin/upload:
    post:
      description: 画像のアップロード
      operationId: admin_upload_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  format: binary
                  type: string
                  x-content-type: image/jpg
                name:
                  type: string
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GachaItem'
          description: 正常なレスポンス
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GachaItem'
          description: リクエストが不正な場合
      x-openapi-router-controller: openapi_server.controllers.security_controller
components:
  schemas:
    GachaItem:
      example:
        pictId: 6
        name: name
        id: 0
        rare: 1
      properties:
        id:
          format: int64
          title: id
          type: integer
        name:
          title: name
          type: string
        pictId:
          format: int64
          title: pictId
          type: string
        rare:
          format: int64
          title: rare
          type: integer
      title: GachaItem
      type: object
    GachaList:
      example:
        gachaList:
        - pictId: 6
          name: name
          id: 0
          rare: 1
        - pictId: 6
          name: name
          id: 0
          rare: 1
      properties:
        gachaList:
          items:
            $ref: '#/components/schemas/GachaItem'
          title: gachaList
          type: array
      title: GachaList
      type: object

