# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class GachaItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, pict_id=None, rare=None):  # noqa: E501
        """GachaItem - a model defined in OpenAPI

        :param id: The id of this GachaItem.  # noqa: E501
        :type id: int
        :param name: The name of this GachaItem.  # noqa: E501
        :type name: str
        :param pict_id: The pict_id of this GachaItem.  # noqa: E501
        :type pict_id: str
        :param rare: The rare of this GachaItem.  # noqa: E501
        :type rare: int
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'pict_id': str,
            'rare': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'pict_id': 'pictId',
            'rare': 'rare'
        }

        self._id = id
        self._name = name
        self._pict_id = pict_id
        self._rare = rare

    @classmethod
    def from_dict(cls, dikt) -> 'GachaItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GachaItem of this GachaItem.  # noqa: E501
        :rtype: GachaItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this GachaItem.


        :return: The id of this GachaItem.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GachaItem.


        :param id: The id of this GachaItem.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this GachaItem.


        :return: The name of this GachaItem.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GachaItem.


        :param name: The name of this GachaItem.
        :type name: str
        """

        self._name = name

    @property
    def pict_id(self):
        """Gets the pict_id of this GachaItem.


        :return: The pict_id of this GachaItem.
        :rtype: str
        """
        return self._pict_id

    @pict_id.setter
    def pict_id(self, pict_id):
        """Sets the pict_id of this GachaItem.


        :param pict_id: The pict_id of this GachaItem.
        :type pict_id: str
        """

        self._pict_id = pict_id

    @property
    def rare(self):
        """Gets the rare of this GachaItem.


        :return: The rare of this GachaItem.
        :rtype: int
        """
        return self._rare

    @rare.setter
    def rare(self, rare):
        """Sets the rare of this GachaItem.


        :param rare: The rare of this GachaItem.
        :type rare: int
        """

        self._rare = rare
