# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.gacha_item import GachaItem
from openapi_server import util

from openapi_server.models.gacha_item import GachaItem  # noqa: E501

class GachaList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, gacha_list=None):  # noqa: E501
        """GachaList - a model defined in OpenAPI

        :param gacha_list: The gacha_list of this GachaList.  # noqa: E501
        :type gacha_list: List[GachaItem]
        """
        self.openapi_types = {
            'gacha_list': List[GachaItem]
        }

        self.attribute_map = {
            'gacha_list': 'gachaList'
        }

        self._gacha_list = gacha_list

    @classmethod
    def from_dict(cls, dikt) -> 'GachaList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GachaList of this GachaList.  # noqa: E501
        :rtype: GachaList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def gacha_list(self):
        """Gets the gacha_list of this GachaList.


        :return: The gacha_list of this GachaList.
        :rtype: List[GachaItem]
        """
        return self._gacha_list

    @gacha_list.setter
    def gacha_list(self, gacha_list):
        """Sets the gacha_list of this GachaList.


        :param gacha_list: The gacha_list of this GachaList.
        :type gacha_list: List[GachaItem]
        """

        self._gacha_list = gacha_list
